import { useMemo, useState } from 'react'
import {
    ResponsiveContainer,
    PieChart,
    Pie,
    Cell,
    Tooltip,
    AreaChart,
    Area,
    CartesianGrid,
    XAxis,
    YAxis,
    Legend,
} from 'recharts'

export default function SIPCalculator() {
    const [monthlyInvestment, setMonthlyInvestment] =
        useState(10000)

    const [investmentPeriod, setInvestmentPeriod] =
        useState(15)

    const [expectedReturn, setExpectedReturn] =
        useState(12)

    const calculations = useMemo(() => {
        const monthlyRate =
            expectedReturn / 12 / 100

        const months = investmentPeriod * 12

        const futureValue =
            monthlyInvestment *
            (((Math.pow(1 + monthlyRate, months) - 1) /
                monthlyRate) *
                (1 + monthlyRate))

        const investedAmount =
            monthlyInvestment * months

        const estimatedReturns =
            futureValue - investedAmount

        return {
            futureValue,
            investedAmount,
            estimatedReturns,
        }
    }, [
        monthlyInvestment,
        investmentPeriod,
        expectedReturn,
    ])

    const pieData = [
        {
            name: 'Invested Amount',
            value: calculations.investedAmount,
        },
        {
            name: 'Estimated Returns',
            value: calculations.estimatedReturns,
        },
    ]

    const growthData = useMemo(() => {
        const data = []

        let total = 0

        const monthlyRate =
            expectedReturn / 12 / 100

        for (
            let year = 1;
            year <= investmentPeriod;
            year++
        ) {
            const months = year * 12

            total =
                monthlyInvestment *
                (((Math.pow(
                    1 + monthlyRate,
                    months
                ) - 1) /
                    monthlyRate) *
                    (1 + monthlyRate))

            data.push({
                year: `Year ${year}`,
                value: Math.round(total),
            })
        }

        return data
    }, [
        monthlyInvestment,
        expectedReturn,
        investmentPeriod,
    ])

    const COLORS = ['#10b981', '#0f172a']

    return (
        <section className="bg-white rounded-[32px] border border-slate-200 shadow-sm overflow-hidden">
            <div className="grid lg:grid-cols-2">
                {/* LEFT SIDE */}
                <div className="p-8 lg:p-10">
                    <div className="mb-10">
                        <div className="inline-flex items-center bg-emerald-50 text-emerald-700 px-4 py-2 rounded-full text-sm font-semibold mb-4">
                            Investment Calculator
                        </div>

                        <h2 className="text-4xl font-bold text-slate-900 mb-3">
                            SIP Calculator
                        </h2>

                        <p className="text-slate-500 leading-relaxed">
                            Calculate future wealth generated by your
                            Systematic Investment Plan (SIP).
                        </p>
                    </div>

                    <div className="space-y-8">
                        {/* Monthly Investment */}
                        <div>
                            <div className="flex items-center justify-between mb-3">
                                <label className="text-sm font-semibold text-slate-700">
                                    Monthly Investment
                                </label>

                                <span className="text-xl font-bold text-emerald-600">
                                    ₹{' '}
                                    {monthlyInvestment.toLocaleString()}
                                </span>
                            </div>

                            <input
                                type="range"
                                min="500"
                                max="200000"
                                step="500"
                                value={monthlyInvestment}
                                onChange={(e) =>
                                    setMonthlyInvestment(
                                        Number(e.target.value)
                                    )
                                }
                                className="w-full accent-emerald-600"
                            />
                        </div>

                        {/* Time Period */}
                        <div>
                            <div className="flex items-center justify-between mb-3">
                                <label className="text-sm font-semibold text-slate-700">
                                    Investment Period
                                </label>

                                <span className="text-xl font-bold text-emerald-600">
                                    {investmentPeriod} Years
                                </span>
                            </div>

                            <input
                                type="range"
                                min="1"
                                max="40"
                                value={investmentPeriod}
                                onChange={(e) =>
                                    setInvestmentPeriod(
                                        Number(e.target.value)
                                    )
                                }
                                className="w-full accent-emerald-600"
                            />
                        </div>

                        {/* Expected Return */}
                        <div>
                            <div className="flex items-center justify-between mb-3">
                                <label className="text-sm font-semibold text-slate-700">
                                    Expected Return Rate
                                </label>

                                <span className="text-xl font-bold text-emerald-600">
                                    {expectedReturn}%
                                </span>
                            </div>

                            <input
                                type="range"
                                min="1"
                                max="30"
                                value={expectedReturn}
                                onChange={(e) =>
                                    setExpectedReturn(
                                        Number(e.target.value)
                                    )
                                }
                                className="w-full accent-emerald-600"
                            />
                        </div>
                    </div>

                    {/* RESULT CARDS */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-10">
                        <div className="bg-slate-50 rounded-2xl p-5 border border-slate-200">
                            <p className="text-slate-500 text-sm mb-2">
                                Invested Amount
                            </p>

                            <h3 className="text-2xl font-bold text-slate-900">
                                ₹{' '}
                                {Math.round(
                                    calculations.investedAmount
                                ).toLocaleString()}
                            </h3>
                        </div>

                        <div className="bg-emerald-50 rounded-2xl p-5 border border-emerald-100">
                            <p className="text-emerald-700 text-sm mb-2">
                                Estimated Returns
                            </p>

                            <h3 className="text-2xl font-bold text-emerald-700">
                                ₹{' '}
                                {Math.round(
                                    calculations.estimatedReturns
                                ).toLocaleString()}
                            </h3>
                        </div>

                        <div className="bg-slate-900 rounded-2xl p-5">
                            <p className="text-slate-400 text-sm mb-2">
                                Total Future Value
                            </p>

                            <h3 className="text-2xl font-bold text-white">
                                ₹{' '}
                                {Math.round(
                                    calculations.futureValue
                                ).toLocaleString()}
                            </h3>
                        </div>
                    </div>
                </div>

                {/* RIGHT SIDE */}
                <div className="bg-gradient-to-br from-slate-900 via-slate-800 to-emerald-900 p-8 lg:p-10 text-white flex flex-col justify-between">
                    {/* TOP */}
                    <div>
                        <div className="flex items-center justify-between mb-8">
                            <div>
                                <p className="text-slate-400 mb-2">
                                    Wealth Projection
                                </p>

                                <h3 className="text-4xl font-bold">
                                    ₹{' '}
                                    {Math.round(
                                        calculations.futureValue
                                    ).toLocaleString()}
                                </h3>
                            </div>

                            <div className="w-16 h-16 rounded-2xl bg-emerald-500/20 border border-emerald-400/20 flex items-center justify-center">
                                📈
                            </div>
                        </div>

                        {/* PIE CHART */}
                        <div className="bg-white/10 backdrop-blur-xl border border-white/10 rounded-3xl p-6 mb-8">
                            <div className="mb-4">
                                <h4 className="text-xl font-semibold">
                                    Investment Breakdown
                                </h4>

                                <p className="text-slate-400 text-sm">
                                    Invested vs wealth gained.
                                </p>
                            </div>

                            <div className="h-72">
                                <ResponsiveContainer
                                    width="100%"
                                    height="100%"
                                >
                                    <PieChart>
                                        <Pie
                                            data={pieData}
                                            cx="50%"
                                            cy="50%"
                                            innerRadius={70}
                                            outerRadius={100}
                                            paddingAngle={5}
                                            dataKey="value"
                                        >
                                            {pieData.map((entry, index) => (
                                                <Cell
                                                    key={index}
                                                    fill={
                                                        COLORS[
                                                        index % COLORS.length
                                                        ]
                                                    }
                                                />
                                            ))}
                                        </Pie>

                                        <Tooltip />

                                        <Legend />
                                    </PieChart>
                                </ResponsiveContainer>
                            </div>
                        </div>
                    </div>

                    {/* AREA CHART */}
                    <div>
                        <div className="mb-4">
                            <h4 className="text-xl font-semibold">
                                Growth Over Time
                            </h4>

                            <p className="text-slate-400 text-sm">
                                Estimated portfolio growth annually.
                            </p>
                        </div>

                        <div className="h-72">
                            <ResponsiveContainer
                                width="100%"
                                height="100%"
                            >
                                <AreaChart data={growthData}>
                                    <defs>
                                        <linearGradient
                                            id="sipGrowth"
                                            x1="0"
                                            y1="0"
                                            x2="0"
                                            y2="1"
                                        >
                                            <stop
                                                offset="5%"
                                                stopColor="#10b981"
                                                stopOpacity={0.8}
                                            />

                                            <stop
                                                offset="95%"
                                                stopColor="#10b981"
                                                stopOpacity={0}
                                            />
                                        </linearGradient>
                                    </defs>

                                    <CartesianGrid
                                        strokeDasharray="3 3"
                                        stroke="#334155"
                                    />

                                    <XAxis
                                        dataKey="year"
                                        stroke="#94a3b8"
                                    />

                                    <YAxis stroke="#94a3b8" />

                                    <Tooltip />

                                    <Area
                                        type="monotone"
                                        dataKey="value"
                                        stroke="#10b981"
                                        fillOpacity={1}
                                        fill="url(#sipGrowth)"
                                    />
                                </AreaChart>
                            </ResponsiveContainer>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    )
}